name: Build LaTeX Resume

on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      # New step to install the Arial font
      - name: Install Microsoft Fonts
        run: |
          sudo apt-get update
          sudo apt-get install -y ttf-mscorefonts-installer
          sudo fc-cache -f -v

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          compiler: xelatex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Resume
          path: resume.pdf
