name: Build LaTeX Resume

on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          # Explicitly tell the action to use the xelatex compiler
          compiler: xelatex

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Resume
          path: resume.pdf
