name: Build LaTeX Resume

on:
  push:
    branches:
      - master

jobs:
  build_latex:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Git repository
        uses: actions/checkout@v4

      # Step to auto-accept the EULA for Microsoft fonts
      - name: Accept EULA
        run: echo "ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true" | sudo debconf-set-selections

      # The main compilation step, now with the font package included
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: resume.tex
          compiler: xelatex
          # This is the key: install the font package inside the action's container
          extra_system_packages: "ttf-mscorefonts-installer"

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: PDF-Resume
          path: resume.pdf
